# Stage 1: Build
FROM node:18-alpine as builder

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy essential configuration files
COPY package.json yarn.lock ./

# Install all dependencies 
RUN yarn install 

# Copy the rest of the application files
COPY . .

# Compile TypeScript code into JavaScript
RUN yarn run build

# Stage 2: Runtime
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy only the necessary files and compiled code from the build stage
COPY package.json yarn.lock ./
COPY --from=builder /usr/src/app/dist ./dist

# Install only production dependencies
RUN yarn install --frozen-lockfile --production

# Expose the required ports for the application
EXPOSE 3000        # REST API port
EXPOSE 40000-49999 # RTC Min/Max Ports for mediasoup
EXPOSE 4443        # WebSocket (Protoo) port

# Set the required environment variables
ENV NODE_ENV=production
ENV PORT=3000

# Default command to start the application
CMD ["node", "dist/main.js"]
