version: '3.7'
services:
  mediasoup:
    build: .
    image: webrtc-server:test
    environment:
      - MEDIASOUP_ANNOUNCED_IP=192.168.10.15
      - PROTOO_LISTEN_PORT=443
      - MEDIASOUP_MIN_PORT=40000
      - MEDIASOUP_MAX_PORT=50000
      - HTTPS_CERT_FULLCHAIN=/config/certs/fullchain.pem
      - HTTPS_CERT_PRIVKEY=/config/certs/privkey.pem
      - MEDIASOUP_CLIENT_ENABLE_ICESERVER=yes
      - MEDIASOUP_CLIENT_ICESERVER_HOST=192.168.10.15
      - MEDIASOUP_CLIENT_ICESERVER_PROTO=udp
      - MEDIASOUP_CLIENT_ICESERVER_PORT=3478
      - MEDIASOUP_CLIENT_ICESERVER_USER=test
      - MEDIASOUP_CLIENT_ICESERVER_PASS=test123
      - MEDIASOUP_CLIENT_PROTOOPORT=443
      - MEDIASOUP_INGRESS_HOST=webrtc.prueba.2060.io
    ports:
      - '443:443'
    volumes:
      - ./certs/fullchain.pem:/config/certs/fullchain.pem
      - ./certs/privkey.pem:/config/certs/privkey.pem
  coturn:
    image: coturn/coturn
    environment:
      - TURN_USER=test:test123
    ports:
      - '3478:3478'
      - '3478:3478/udp'
