version: '3.9'

services:
  loadbalancer-webrtc:
    build: .
    image: loadbalancer-webrtc:test
    container_name: loadbalancer-webrtc
    environment:
      - LOG_LEVEL=3
      - APP_PORT=3000
      - REDIS_URL=redis://redis:6379
      - HEALTH_CHECK_INTERVAL=20000
    restart: always
    ports:
      - 3000:3000
    networks:
      - loadbalancing
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - loadbalancing
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru

networks:
  loadbalancing:
    external: true
