version: '3.9'

services:
  loadbalancer-webrtc:
    build: .
    image: loadbalancer-webrtc:test
    container_name: loadbalancer-webrtc
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      APP_PORT: ${APP_PORT}
      REDIS_URL: ${REDIS_URL}
      HEALTH_CHECK_INTERVAL: ${HEALTH_CHECK_INTERVAL}
    restart: always
    ports:
      - 3000:3000
    networks:
      - loadbalancing
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - loadbalancing
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru

networks:
  loadbalancing:
    external: true
