version: '3.7'
services:
  mediasoup:
    build: .
    image: webrtc-server:test
    environment:
      - LOG_LEVEL=3
      - MEDIASOUP_ANNOUNCED_IP=192.168.100.84
      - MEDIASOUP_LISTEN_IP=192.168.100.84
      - PROTOO_LISTEN_PORT=4443
      - MEDIASOUP_MIN_PORT=40000
      - MEDIASOUP_MAX_PORT=50000
      - HTTPS_CERT_FULLCHAIN=/config/certs/fullchain.pem
      - HTTPS_CERT_PRIVKEY=/config/certs/privkey.pem
      - MEDIASOUP_CLIENT_ENABLE_ICESERVER=yes
      - MEDIASOUP_CLIENT_ICESERVER_HOST=192.168.100.84
      - MEDIASOUP_CLIENT_ICESERVER_PROTO=udp
      - MEDIASOUP_CLIENT_ICESERVER_PORT=3478
      - MEDIASOUP_CLIENT_ICESERVER_USER=test
      - MEDIASOUP_CLIENT_ICESERVER_PASS=test123
      - MEDIASOUP_CLIENT_PROTOOPORT=4443
      - MEDIASOUP_INGRESS_HOST=webrtc.prueba.2060.io
      - REDIS_URL=redis://redis:6379
    ports:
      - '4443:4443'
    volumes:
      - ./certs/fullchain.pem:/config/certs/fullchain.pem
      - ./certs/privkey.pem:/config/certs/privkey.pem
  coturn:
    image: coturn/coturn
    environment:
      - TURN_USER=test:test123
    volumes:
      - ./certs/turnserver.conf:/etc/turnserver.conf
    ports:
      - '3478:3478'
      - '3478:3478/udp'

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru
