# Increase this value when you want install a new instance webrtc-server
# instanceId: 1

namespace:
  name: default

# Service configuration
service:
  # Recommended for multi-instance mode: Use instanceId to differentiate service names.
  # name: webrtc-server-{{ .Values.instanceId }}-service
  name: webrtc-demos-service

# Ingress configuration
ingress:
  # Recommended for multi-instance mode: Use instanceId to differentiate ingress names and hosts.
  # name: webrtc-server-{{ .Values.instanceId }}-ingress
  # host: webrtc-server-{{ .Values.instanceId }}.example.io
  # tlsSecret: webrtc-server-{{ .Values.instanceId }}.example.io-cert
  name: webrtc-demos-ingress
  host: webrtc.example.io
  tlsSecret: webrtc.example.io-cert
  loadBalancerMode: false # Set to true if you want to use a load balancer for the /rooms endpoint

# Application name used in labels
app:
  # Recommended for multi-instance mode: Use instanceId to differentiate application names.
  # name: webrtc-server-{{ .Values.instanceId }}
  name: webrtc-demos

# StatefulSet configuration
statefulset:
  # Recommended for multi-instance mode: Use instanceId to differentiate StatefulSet names and container names.
  # name: webrtc-server-{{ .Values.instanceId }}
  # serviceName: "webrtc-server-{{ .Values.instanceId }}-service"
  # containerName: webrtc-server-container-{{ .Values.instanceId }}
  name: webrtc-demos
  serviceName: "webrtc-demos-service"
  replicas: 1
  containerName: webrtc-demos-container
  pullPolicy: Always
  storage: 1Gi
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

# Environment variables
env:
  LOG_LEVEL: "3"
  DEBUG: "*mediasoup* *INFO* *WARN* *ERROR*"
  PROTOO_LISTEN_PORT: "4443"
  MEDIASOUP_CLIENT_PROTOOPORT: "443"
  MEDIASOUP_CLIENT_ENABLE_ICESERVER: "yes"
  MEDIASOUP_CLIENT_ICESERVER_HOST: "xxx.xxx.xxx.xxx"
  MEDIASOUP_CLIENT_ICESERVER_PROTO: "udp"
  MEDIASOUP_CLIENT_ICESERVER_PORT: "3478"
  MEDIASOUP_CLIENT_ICESERVER_USER: "user"
  MEDIASOUP_CLIENT_ICESERVER_PASS: "password"
  # Recommended for multi-instance mode: Use instanceId to differentiate ingress hosts.
  # MEDIASOUP_INGRESS_HOST: "webrtc-server-{{ .Values.instanceId }}.example.io"
  MEDIASOUP_INGRESS_HOST: "webrtc.example.io"
  HTTPS_CERT_FULLCHAIN: "/config/certificates/tls.crt"
  HTTPS_CERT_PRIVKEY: "/config/certificates/tls.key"

  # Secret configuration
secret:
  # Recommended for multi-instance mode: Use instanceId to differentiate secret names.
  # name: webrtc-server-{{ .Values.instanceId }}.example.io-cert
  name: webrtc.example.io-cert

extraEnv: []
# extraEnv: 
#   - name: LOADBALANCER_URL
#     value: "http://webrtc-loadbalancer.2060-core-dev"
#   - name: SERVICE_URL
#     value: "https://webrtc-server-{{ .Values.instanceId }}-service.2060-core-dev"