version: '3.7'
services:
  mediasoup1:
    build: .
    image: webrtc-server:test
    container_name: mediasoup1
    networks:
      mediasoup_net:
        ipv4_address: 192.168.10.11
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      MEDIASOUP_ANNOUNCED_IP: ${MEDIASOUP1_ANNOUNCED_IP}
      PROTOO_LISTEN_PORT: ${MEDIASOUP1_PROTOO_LISTEN_PORT}
      MEDIASOUP_MIN_PORT: ${MEDIASOUP1_MIN_PORT}
      MEDIASOUP_MAX_PORT: ${MEDIASOUP1_MAX_PORT}
      MEDIASOUP_NUM_WORKERS: ${MEDIASOUP1_NUM_WORKERS}
      HTTPS_CERT_FULLCHAIN: ${HTTPS_CERT_FULLCHAIN}
      HTTPS_CERT_PRIVKEY: ${HTTPS_CERT_PRIVKEY}
      REDIS_URL: ${REDIS_URL}
      MEDIASOUP_CLIENT_ENABLE_ICESERVER: ${MEDIASOUP1_CLIENT_ENABLE_ICESERVER}
      MEDIASOUP_CLIENT_ICESERVER_HOST: ${MEDIASOUP1_ICESERVER_HOST}
      MEDIASOUP_CLIENT_ICESERVER_PROTO: ${MEDIASOUP_CLIENT_ICESERVER_PROTO}
      MEDIASOUP_CLIENT_ICESERVER_PORT: ${MEDIASOUP_CLIENT_ICESERVER_PORT}
      MEDIASOUP_CLIENT_ICESERVER_USER: ${MEDIASOUP_CLIENT_ICESERVER_USER}
      MEDIASOUP_CLIENT_ICESERVER_PASS: ${MEDIASOUP_CLIENT_ICESERVER_PASS}
      MEDIASOUP_CLIENT_PROTOOPORT: ${MEDIASOUP1_CLIENT_PROTOOPORT}
      MEDIASOUP_INGRESS_HOST: ${MEDIASOUP1_INGRESS_HOST}
    ports:
      - '4443:4443'
    volumes:
      - ./certs/fullchain.pem:/config/certs/fullchain.pem
      - ./certs/privkey.pem:/config/certs/privkey.pem

  mediasoup2:
    build: .
    image: webrtc-server:test
    container_name: mediasoup2
    networks:
      mediasoup_net:
        ipv4_address: 192.168.10.12
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      MEDIASOUP_ANNOUNCED_IP: ${MEDIASOUP2_ANNOUNCED_IP}
      PROTOO_LISTEN_PORT: ${MEDIASOUP2_PROTOO_LISTEN_PORT}
      MEDIASOUP_MIN_PORT: ${MEDIASOUP2_MIN_PORT}
      MEDIASOUP_MAX_PORT: ${MEDIASOUP2_MAX_PORT}
      MEDIASOUP_NUM_WORKERS: ${MEDIASOUP2_NUM_WORKERS}
      HTTPS_CERT_FULLCHAIN: ${HTTPS_CERT_FULLCHAIN}
      HTTPS_CERT_PRIVKEY: ${HTTPS_CERT_PRIVKEY}
      REDIS_URL: ${REDIS_URL}
      MEDIASOUP_CLIENT_ENABLE_ICESERVER: ${MEDIASOUP2_CLIENT_ENABLE_ICESERVER}
      MEDIASOUP_CLIENT_ICESERVER_HOST: ${MEDIASOUP2_ICESERVER_HOST}
      MEDIASOUP_CLIENT_ICESERVER_PROTO: ${MEDIASOUP_CLIENT_ICESERVER_PROTO}
      MEDIASOUP_CLIENT_ICESERVER_PORT: ${MEDIASOUP_CLIENT_ICESERVER_PORT}
      MEDIASOUP_CLIENT_ICESERVER_USER: ${MEDIASOUP_CLIENT_ICESERVER_USER}
      MEDIASOUP_CLIENT_ICESERVER_PASS: ${MEDIASOUP_CLIENT_ICESERVER_PASS}
      MEDIASOUP_CLIENT_PROTOOPORT: ${MEDIASOUP2_CLIENT_PROTOOPORT}
      MEDIASOUP_INGRESS_HOST: ${MEDIASOUP2_INGRESS_HOST}
    ports:
      - '4444:4444'
    volumes:
      - ./certs/fullchain.pem:/config/certs/fullchain.pem
      - ./certs/privkey.pem:/config/certs/privkey.pem

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      mediasoup_net:
        ipv4_address: 192.168.10.10
    ports:
      - '6379:6379'
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru

networks:
  mediasoup_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
