version: "3.7"
services:
  mediasoup:
    build: .
    image: webrtc-server:test
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      MEDIASOUP_ANNOUNCED_IP: ${MEDIASOUP_ANNOUNCED_IP}
      MEDIASOUP_LISTEN_IP: ${MEDIASOUP_LISTEN_IP}
      PROTOO_LISTEN_PORT: ${PROTOO_LISTEN_PORT}
      MEDIASOUP_MIN_PORT: ${MEDIASOUP_MIN_PORT}
      MEDIASOUP_MAX_PORT: ${MEDIASOUP_MAX_PORT}
      MEDIASOUP_NUM_WORKERS: ${MEDIASOUP_NUM_WORKERS}
      HTTPS_CERT_FULLCHAIN: ${HTTPS_CERT_FULLCHAIN}
      HTTPS_CERT_PRIVKEY: ${HTTPS_CERT_PRIVKEY}
      MEDIASOUP_CLIENT_ENABLE_ICESERVER: ${MEDIASOUP_CLIENT_ENABLE_ICESERVER}
      MEDIASOUP_CLIENT_ICESERVER_HOST: ${MEDIASOUP_CLIENT_ICESERVER_HOST}
      MEDIASOUP_CLIENT_ICESERVER_PROTO: ${MEDIASOUP_CLIENT_ICESERVER_PROTO}
      MEDIASOUP_CLIENT_ICESERVER_PORT: ${MEDIASOUP_CLIENT_ICESERVER_PORT}
      MEDIASOUP_CLIENT_ICESERVER_USER: ${MEDIASOUP_CLIENT_ICESERVER_USER}
      MEDIASOUP_CLIENT_ICESERVER_PASS: ${MEDIASOUP_CLIENT_ICESERVER_PASS}
      MEDIASOUP_CLIENT_PROTOOPORT: ${MEDIASOUP_CLIENT_PROTOOPORT}
      MEDIASOUP_INGRESS_HOST: ${MEDIASOUP_INGRESS_HOST}
      LOADBALANCER_URL: ${LOADBALANCER_URL}
      SERVICE_URL: ${SERVICE_URL}
    ports:
      - "443:4443"
    networks:
      - webrtc_network
    volumes:
      - ./certs/fullchain.pem:/config/certs/fullchain.pem
      - ./certs/privkey.pem:/config/certs/privkey.pem

  coturn:
    image: coturn/coturn
    environment:
      TURN_USER: ${TURN_USER}
    volumes:
      - ./certs/turnserver.conf:/etc/turnserver.conf
    ports:
      - "3478:3478"
      - "3478:3478/udp"
    networks:
      - webrtc_network

networks:
  webrtc_network:
    driver: bridge
