global:
  domain: example.io

configMap:
  name: webrtc-client-demos-config
  serverName: webrtc.{{ .Values.global.domain }}
  protooPort: 443

secret:
  name: webrtc-webclient.{{ .Values.global.domain }}-cert
       
deployment:
  name: webrtc-webclient
  labels:
    app: webrtc-webclient
  pullPolicy: Always
  replicas: 1
  resources: # Default resources requests and limits for the container
    limits:
      memory: "512Mi"
      cpu: "1"
    requests:
      memory: "256Mi"
      cpu: "0.5"

service:
  name: webrtc-client-demos-service
  ports:
    https: 443

ingress:
  name: webrtc-client-demos-ingress
  enabled: true
  host: webrtc-webclient.{{ .Values.global.domain }}
  tlsSecret: webrtc-webclient.{{ .Values.global.domain }}-cert
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS  