global:
  domain: example.io

name: webrtc-pymediasoup-client
replicas: 1
backend: 
  env:
    flask_app: app.py
    flask_env: test
    debug: 1
    pythonunbuffered: 1
    video_url: https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_2mb.mp4