name: webrtc-pymediasoup-client
namespace: default
replicas: 1
images:
  backend: 
    repository: io2060/webrtc-pymediasoup-client
    tag: dev
    env:
      flask_app: app.py
      flask_env: test
      debug: 1
      pythonunbuffered: 1
      video_url: https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_2mb.mp4
      domain: example.io