name: Continuous Deployment

on:
  push:
    branches: [main, 'release/**']
  workflow_dispatch:

env:
  DH_USERNAME: ${{ secrets.DOCKER_HUB_LOGIN }}
  DH_TOKEN: ${{ secrets.DOCKER_HUB_PWD }}
  IMAGE_TAG: ${{ github.ref == 'refs/heads/main' && 'dev' || github.ref }}

jobs:
  build-and-push:
    name: Build and push Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install
      
      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Run semantic release
        uses: codfish/semantic-release-action@v3
        id: semantic
        with:
          branches: |
            [
              'release',
              { 
                name: 'main',
                prerelease: 'dev'
              }
            ]
          plugins: |
            [
              [
                "@semantic-release/commit-analyzer",
                {
                  "preset": "angular",
                  "releaseRules": [
                    {
                      "type": "refactor",
                      "release": "patch"
                    }
                  ]
                }
              ],
              [
                "@semantic-release/npm",
                {
                  "npmPublish": false
                }
              ],
              "@semantic-release/release-notes-generator"
            ]

      - name: Log in to Docker Hub
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          echo "$DH_TOKEN" | docker login -u "$DH_USERNAME" --password-stdin

      - name: Build Docker images
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          for APP in webrtc-server loadbalancer; do
            IMAGE_NAME=$APP
            if [ "$APP" == "loadbalancer" ]; then
              IMAGE_NAME="webrtc-loadbalancer"
            fi
            cp pnpm-lock.yaml apps/$APP/
            docker build -f apps/$APP/Dockerfile -t $DH_USERNAME/$IMAGE_NAME:$IMAGE_TAG apps/$APP/
          done

      - name: Add tags to Docker images and push to Docker Hub
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          for APP in webrtc-server loadbalancer; do
            IMAGE_NAME=$APP
            if [ "$APP" == "loadbalancer" ]; then
              IMAGE_NAME="webrtc-load-balancer"
            fi
            docker tag $DH_USERNAME/$IMAGE_NAME:$IMAGE_TAG $DH_USERNAME/$IMAGE_NAME:v${RELEASE_MAJOR}-$IMAGE_TAG
            docker tag $DH_USERNAME/$IMAGE_NAME:$IMAGE_TAG $DH_USERNAME/$IMAGE_NAME:v${RELEASE_MAJOR}.${RELEASE_MINOR}-$IMAGE_TAG
            docker tag $DH_USERNAME/$IMAGE_NAME:$IMAGE_TAG $DH_USERNAME/$IMAGE_NAME:v${RELEASE_MAJOR}.${RELEASE_MINOR}.${RELEASE_PATCH:0:1}-$IMAGE_TAG
            docker tag $DH_USERNAME/$IMAGE_NAME:$IMAGE_TAG $DH_USERNAME/$IMAGE_NAME:v$RELEASE_VERSION

            docker push $DH_USERNAME/$IMAGE_NAME:$IMAGE_TAG
            docker push $DH_USERNAME/$IMAGE_NAME:v$RELEASE_MAJOR-$IMAGE_TAG
            docker push $DH_USERNAME/$IMAGE_NAME:v$RELEASE_MAJOR.$RELEASE_MINOR-$IMAGE_TAG
            docker push $DH_USERNAME/$IMAGE_NAME:v$RELEASE_MAJOR.$RELEASE_MINOR.${RELEASE_PATCH:0:1}-$IMAGE_TAG
            docker push $DH_USERNAME/$IMAGE_NAME:v$RELEASE_VERSION
          done

      - name: Log in to Docker Hub Helm Registry
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          echo "$DH_TOKEN" | helm registry login -u "$DH_USERNAME" --password-stdin docker.io

      - name: Push Helm charts to Docker Hub OCI repo
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          for chart in ./charts/*; do
            if [ -d "$chart" ]; then
              chart_name=$(basename "$chart")
              sed -i "s/^version:.*/version: $IMAGE_TAG/" "$chart/Chart.yaml"
              helm dependency update "$chart"
              helm package "$chart" -d ./charts
              helm push ./charts/"$chart_name"-$IMAGE_TAG.tgz oci://docker.io/$DH_USERNAME
            fi
          done
        